import java.util.Scanner;

public class Main {
    public static void main(String[] args) throws Exception {

        //get user input
        Scanner input = new Scanner(System.in);
        System.out.print("Enter number: ");
        int len = input.nextInt();

        //generate an array to be shared then pass to the thread
        FibonacciArray fibArray = new FibonacciArray(len);
        FibonacciThread t1 = new FibonacciThread(fibArray, 1);
        
        //start the thread
        t1.start();

        //wait until the child thread finishes execution
        t1.join();

        //when the thread finishes execution, the parent thread will output the sequence generated by the child thread
        fibArray.print();
    }
}
